repository:
    path: github.com/mesosphere/mesos_exporter
tarball:
    files:
        - LICENSE
crossbuild:
    platforms:
        - linux/amd64
        - linux/386
        - darwin/amd64
        - darwin/386
        - linux/arm
        - linux/arm64
        - linux/ppc64
        - linux/ppc64le
